version: '3'
services:
    postgres:
        build: "./flyway/docker/make"
        ports:
            - "5432:5432"
        restart: always
        environment:
            POSTGRES_DB: sample
            POSTGRES_USER: sample
            POSTGRES_PASSWORD: weak-password
            PGPORT: 5432
            # postgres tde parameter
            PGTDE_CIPHER: cipher-password
            PGTDE_ALGO: aes
            TZ: "Asia/Tokyo"
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
        command: 'postgres -c config_file="/etc/postgresql.conf"'
        volumes:
            - ./flyway/docker/init.sh:/docker-entrypoint-initdb.d/init.sh
            - ./flyway/docker/conf/postgresql.conf:/etc/postgresql.conf
            - ./dump_datas:/var/dump_datas
            - postgres-data:/var/lib/postgresql/data
        networks:
            - standard
networks:
    standard:
        driver: bridge
volumes:
    postgres-data:
        external: true